# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_auto_20160222_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('pct', models.DecimalField(decimal_places=3, max_digits=3)),
                ('gb', models.DecimalField(decimal_places=1, max_digits=3)),
                ('home_wins', models.IntegerField()),
                ('home_losses', models.IntegerField()),
                ('road_wins', models.IntegerField()),
                ('road_losses', models.IntegerField()),
                ('division_wins', models.IntegerField()),
                ('division_losses', models.IntegerField()),
                ('conference_wins', models.IntegerField()),
                ('conference_losses', models.IntegerField()),
                ('ppg', models.DecimalField(decimal_places=1, max_digits=4)),
                ('opp_ppg', models.DecimalField(decimal_places=1, max_digits=4)),
                ('pt_diff', models.DecimalField(decimal_places=1, max_digits=4)),
                ('win_streak', models.IntegerField()),
                ('last_10_wins', models.IntegerField()),
                ('last_10_losses', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba.Team')),
            ],
        ),
    ]
