# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0003_standings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standings',
            name='year',
            field=models.DateTimeField(),
        ),
    ]
