# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0006_auto_20160223_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.CharField(choices=[('E', 'Eastern'), ('W', 'Western')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('A', 'Atlantic'), ('C', 'Central'), ('SE', 'Southeast'), ('P', 'Pacific'), ('NW', 'Northwest'), ('SW', 'Southwest')], max_length=50)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba.Conference')),
            ],
        ),
        migrations.AlterModelOptions(
            name='standings',
            options={'verbose_name_plural': 'Standings'},
        ),
    ]
