# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0008_auto_20160223_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nba.Division'),
        ),
    ]
